  global:
    # The smarthost and SMTP sender used for mail notifications.
    smtp_smarthost: 'localhost:25'
    smtp_from: 'alertmanager@example.org'

  route:
    receiver: "alerta"
    group_by: ['alertname']
    group_wait:      15s
    group_interval:  15s
    repeat_interval: 1m

  receivers:
  - name: "alerto"
    webhook_configs:
    - url: 'http://alerta:8080/api/webhooks/prometheus'
      send_resolved: true
      http_config:
       tls_config:
         insecure_skip_verify: false

      headers:
       - header_key: "ST2_API_TOKEN"
         header_value: "blah"
       - header_key: "app"
         header_value: "stack"
  - name: "alerta"
    triton_configs:
    - image: "IMAGE ID"
      package: "package name"
      networks:
        - "NETWORK ID"
      key: "KEY ID"
      cloud_api: "CLOUD_API_URL"
      account: "TRITON_ACCOUNT"
      count: COUNT_OF_INSTANCES
      services:
        - "CNS NAMES"
        - "CNS NAMES"
        - "CNS NAMES"


